package com.annaginagili.easychess

import android.widget.ImageView
import com.annaginagili.easychess.databinding.ActivityBlackGameBinding

object BlackClick {
    fun setClick(binding: ActivityBlackGameBinding): List<ImageView> {
        return listOf(
            binding.a1,
            binding.b1,
            binding.c1,
            binding.d1,
            binding.e1,
            binding.f1,
            binding.g1,
            binding.h1,
            binding.a2,
            binding.b2,
            binding.c2,
            binding.d2,
            binding.e2,
            binding.f2,
            binding.g2,
            binding.h2,
            binding.a3,
            binding.b3,
            binding.c3,
            binding.d3,
            binding.e3,
            binding.f3,
            binding.g3,
            binding.h3,
            binding.a4,
            binding.b4,
            binding.c4,
            binding.d4,
            binding.e4,
            binding.f4,
            binding.g4,
            binding.h4,
            binding.a5,
            binding.b5,
            binding.c5,
            binding.d5,
            binding.e5,
            binding.f5,
            binding.g5,
            binding.h5,
            binding.a6,
            binding.b6,
            binding.c6,
            binding.d6,
            binding.e6,
            binding.f6,
            binding.g6,
            binding.h6,
            binding.a7,
            binding.b7,
            binding.c7,
            binding.d7,
            binding.e7,
            binding.f7,
            binding.g7,
            binding.h7,
            binding.a8,
            binding.b8,
            binding.c8,
            binding.d8,
            binding.e8,
            binding.f8,
            binding.g8,
            binding.h8,
        )
    }
}